version: '2'
services:

  test:
    build:
      dockerfile: Dockerfile.test
      context: .
    volumes:
      - ./:/src
    command: >
      py.test -v -s
      --pdb
      --cov mlsl
      mlsl/tests
